//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongBanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.PHIEUDATCHOes = new HashSet<PHIEUDATCHO>();
            this.VECHUYENBAYs = new HashSet<VECHUYENBAY>();
        }

        public int ID { get; set; }
        [Display(Name = "Mã chuy?n bay")]
        public string IDChuyenBay { get; set; }

        [Display(Name = "Hãng bay")]
        public string HangBay { get; set; }

        [Display(Name = "Sân bay ?i")]
        public string IDSanBayDi { get; set; }

        [Display(Name = "Sân bay ??n")]
        public string IDSanBayDen { get; set; }

        [Display(Name = "Giá ti?n")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [DataType(DataType.Currency)]
        public int GiaTien { get; set; }

        [Display(Name = "Ngày bay")]
        [DataType(DataType.Date)]
        public System.DateTime NgayBay { get; set; } = DateTime.Now;

        [Display(Name = "Gi? bay")]
        public System.TimeSpan GioBay { get; set; }

        [Display(Name = "Th?i gian t?i d? ki?n")]
        public System.TimeSpan ThoiGianToiDuKien { get; set; }

        [Display(Name = "S? gh? h?ng 1")]
        public int SoGheHang1 { get; set; }

        [Display(Name = "S? gh? h?ng 2")]
        public int SoGheHang2 { get; set; }
        public string Status { get; set; }
    
        public virtual HANGBAY HANGBAY1 { get; set; }
        public virtual MAYBAY MAYBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATCHO> PHIEUDATCHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VECHUYENBAY> VECHUYENBAYs { get; set; }
    }
}
