//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongBanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATCHO
    {
        public int ID { get; set; }
        public string IDDatCho { get; set; }
        public int IDChuyenBay { get; set; }
        public string CMND { get; set; }
        public int GiaTien { get; set; }
        public string LoaiVe { get; set; }
        public string Status { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual HANHKHACH HANHKHACH { get; set; }
    }
}
